"""
Agent Tool Registry — Domain Models for ToolDefinition, ToolProposal, and ToolExecutionResult.
"""

from __future__ import annotations

import uuid
from typing import Any

from pydantic import BaseModel, Field

from backend.agents.tools.domain.enums import ToolCategory


class ToolDefinition(BaseModel):
    """
    Structured tool schema definition exposed to AI Agents.
    Maps deterministically to a Command and required AgentCapabilities.
    """

    tool_id: str = Field(description="Unique tool identifier e.g. employee.get")
    name: str = Field(description="Human readable tool name e.g. Get Employee Details")
    description: str = Field(description="Clear tool purpose description for prompt context")
    version: str = Field(default="1.0.0")
    category: ToolCategory = Field(default=ToolCategory.CUSTOM)
    input_schema: dict[str, Any] = Field(default_factory=dict, description="JSON schema for input arguments")
    output_schema: dict[str, Any] = Field(default_factory=dict, description="JSON schema for output results")
    resource: str = Field(description="Target resource domain e.g. employee")
    action: str = Field(description="Target action e.g. read, create, update, terminate")
    required_capabilities: list[str] = Field(
        default_factory=list, description="Capability tokens required e.g. ['employee:read']"
    )
    risk_level: str = Field(default="LOW", description="LOW, MEDIUM, HIGH, CRITICAL")
    requires_hitl: bool = Field(default=False)
    allowed_agent_types: list[str] = Field(default_factory=list, description="Agent types permitted to discover tool")
    enabled: bool = Field(default=True)
    command_type: str = Field(description="Target CommandBus command type e.g. employee.create")
    metadata: dict[str, Any] = Field(default_factory=dict)


class ToolProposal(BaseModel):
    """
    Structured proposal generated by the LLM reasoning engine.
    """

    proposal_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    tool_id: str = Field(description="Target tool identifier")
    arguments: dict[str, Any] = Field(default_factory=dict, description="Arguments proposed by LLM")
    reasoning_step_id: str = Field(default="")
    correlation_id: str = Field(default_factory=lambda: str(uuid.uuid4()))


class ToolExecutionResult(BaseModel):
    """
    Execution result returned to the LLM reasoning engine.
    """

    proposal_id: str
    tool_id: str
    status: str = Field(description="SUCCEEDED, FAILED, WAITING_APPROVAL, REJECTED")
    data: dict[str, Any] = Field(default_factory=dict)
    error: str | None = Field(default=None)
