"""HRMS Domain — Survey, Feedback, EmployeeSentiment."""

from __future__ import annotations

from datetime import date, datetime
from enum import StrEnum
from typing import Any

from pydantic import Field

from backend.hrms.domain.common import HRMSBaseModel, SentimentScore, generate_id, utc_now


class SurveyStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    CLOSED = "CLOSED"
    ARCHIVED = "ARCHIVED"


class Survey(HRMSBaseModel):
    """An HR survey distributed to employees."""

    survey_id: str = Field(default_factory=generate_id)
    organization_id: str
    title: str
    description: str | None = Field(default=None)
    survey_type: str = Field(
        default="GENERAL",
        description="e.g. 'ENGAGEMENT', 'EXIT', 'ONBOARDING', 'PULSE', 'GENERAL'",
    )
    status: SurveyStatus = Field(default=SurveyStatus.DRAFT)
    questions: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Survey questions in structured format",
    )
    target_departments: list[str] = Field(default_factory=list)
    target_employee_ids: list[str] = Field(default_factory=list)
    is_anonymous: bool = Field(default=True)
    start_date: date | None = Field(default=None)
    end_date: date | None = Field(default=None)
    response_count: int = Field(default=0, ge=0)
    created_by: str
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)


class Feedback(HRMSBaseModel):
    """
    A feedback submission (survey response or direct feedback).

    Feedback may be anonymous — employee_id is nullable.
    """

    feedback_id: str = Field(default_factory=generate_id)
    organization_id: str
    survey_id: str | None = Field(default=None)
    employee_id: str | None = Field(
        default=None,
        description="[PII:CONFIDENTIAL] Null if feedback is anonymous",
    )
    department_id: str | None = Field(default=None)
    feedback_type: str = Field(default="SURVEY", description="'SURVEY', 'DIRECT', 'EXIT'")
    responses: dict[str, Any] = Field(
        default_factory=dict,
        description="Question ID → response value mapping",
    )
    open_text: str | None = Field(default=None)
    is_anonymous: bool = Field(default=True)
    submitted_at: datetime = Field(default_factory=utc_now)


class EmployeeSentiment(HRMSBaseModel):
    """
    AI-analyzed sentiment record for an employee or aggregate group.

    Generated by the Sentiment Analysis Agent from feedback, surveys,
    and communication patterns (with consent).
    [PII:SENSITIVE] if tied to a specific employee.
    """

    sentiment_id: str = Field(default_factory=generate_id)
    organization_id: str
    employee_id: str | None = Field(
        default=None,
        description="[PII:SENSITIVE] Null for department/org aggregate analysis",
    )
    department_id: str | None = Field(default=None)
    analysis_period: str = Field(description="e.g. '2024-Q1' or '2024-01'")
    overall_sentiment: SentimentScore
    satisfaction_score: float = Field(ge=0.0, le=10.0)
    engagement_score: float | None = Field(default=None, ge=0.0, le=10.0)
    wellbeing_score: float | None = Field(default=None, ge=0.0, le=10.0)
    attrition_risk_score: float | None = Field(default=None, ge=0.0, le=1.0, description="Predicted attrition probability")
    key_themes: list[str] = Field(
        default_factory=list,
        description="Top sentiment themes identified by AI (e.g. 'workload', 'career growth')",
    )
    source_feedback_ids: list[str] = Field(
        default_factory=list,
        description="Feedback IDs used in this analysis",
    )
    ai_decision_id: str | None = Field(default=None)
    is_aggregate: bool = Field(default=False, description="True if this is a department/org aggregate")
    analyzed_at: datetime = Field(default_factory=utc_now)
    created_at: datetime = Field(default_factory=utc_now)
