"""
LLM Provider Abstraction, Tool Calling & Model Contracts.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from collections.abc import Sequence
from datetime import UTC, datetime
from typing import Any, Generic, TypeVar

from pydantic import BaseModel, Field

T = TypeVar("T", bound=BaseModel)


class TokenUsage(BaseModel):
    """Token consumption metrics for cost accounting."""

    prompt_tokens: int = Field(ge=0, default=0)
    completion_tokens: int = Field(ge=0, default=0)
    total_tokens: int = Field(ge=0, default=0)
    estimated_cost_usd: float = Field(ge=0.0, default=0.0)


class ModelResponse(BaseModel):
    """Raw text completion response from an LLM."""

    content: str
    model_name: str
    provider: str
    usage: TokenUsage
    latency_ms: int = Field(ge=0, default=0)
    created_at: datetime = Field(default_factory=lambda: datetime.now(tz=UTC))


class StructuredModelResponse(BaseModel, Generic[T]):
    """Parsed structured response conforming to strict Pydantic model T."""

    data: T
    raw_content: str
    model_name: str
    provider: str
    usage: TokenUsage
    latency_ms: int = Field(ge=0, default=0)


class ToolCallProposal(BaseModel):
    """Structured proposal from an LLM invoking a specific tool."""

    call_id: str = Field(description="Unique tool call identifier generated by provider/gateway")
    tool_id: str = Field(description="Identifier or name of the target tool")
    tool_name: str = Field(default="")
    arguments: dict[str, Any] = Field(default_factory=dict, description="Parsed structured argument mapping")
    raw_arguments: str | None = None


class ToolCallResponse(BaseModel):
    """LLM response containing one or more structured tool call proposals or textual thought."""

    content: str = ""
    tool_calls: list[ToolCallProposal] = Field(default_factory=list)
    model_name: str
    provider: str
    usage: TokenUsage
    latency_ms: int = Field(ge=0, default=0)
    finish_reason: str = "tool_calls"


class LLMProvider(ABC):
    """Abstract provider interface for all LLM backends."""

    @property
    @abstractmethod
    def provider_name(self) -> str:
        """Name of provider backend."""
        pass

    @abstractmethod
    async def generate_text(
        self,
        prompt: str,
        system_instruction: str | None = None,
        model: str | None = None,
        temperature: float = 0.2,
        max_tokens: int = 1024,
    ) -> ModelResponse:
        """Generate text completion from prompt."""
        pass

    @abstractmethod
    async def generate_structured(
        self,
        prompt: str,
        response_schema: type[T],
        system_instruction: str | None = None,
        model: str | None = None,
        temperature: float = 0.0,
    ) -> StructuredModelResponse[T]:
        """Generate guaranteed structured output validating against schema T."""
        pass

    @abstractmethod
    async def generate_tool_calls(
        self,
        prompt: str,
        tools: list[dict[str, Any]],
        system_instruction: str | None = None,
        model: str | None = None,
        temperature: float = 0.0,
        tool_choice: str | dict[str, Any] = "auto",
    ) -> ToolCallResponse:
        """Generate structured tool calls from available tools."""
        pass

    @abstractmethod
    async def embed_text(self, text: str, model: str | None = None) -> Sequence[float]:
        """Generate vector embedding for text."""
        pass
