"""
AI Intelligence Layer — Recommendation contracts.

AI recommendations are advisory outputs generated by agents.
They are distinct from AIDecisions — a recommendation suggests an action,
while a decision is a concluded judgment.

Recommendations flow through HITL when risk is HIGH/CRITICAL.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field

from backend.governance.risk import RiskLevel


class RecommendationStatus(StrEnum):
    """Lifecycle status of an AI recommendation."""

    PENDING = "PENDING"  # Generated, awaiting human review
    ACCEPTED = "ACCEPTED"  # Human accepted the recommendation
    REJECTED = "REJECTED"  # Human rejected the recommendation
    ACTED_UPON = "ACTED_UPON"  # Recommendation was executed (autonomously or after approval)
    EXPIRED = "EXPIRED"  # Recommendation window elapsed
    SUPERSEDED = "SUPERSEDED"  # Replaced by a newer recommendation


class AIRecommendation(BaseModel):
    """
    An AI-generated recommendation for a specific HR action or decision.

    Examples:
    - "Recommend promoting Employee X based on KPI performance"
    - "Recommend training program Y for skill gap in department Z"
    - "Flag Employee A as high attrition risk — suggest retention action"
    """

    recommendation_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    recommendation_type: str = Field(description="Type, e.g. 'promotion_recommendation'")
    title: str
    description: str

    # Subject
    subject_type: str = Field(description="Type of entity being recommended about, e.g. 'Employee'")
    subject_id: str = Field(description="ID of the subject entity")

    # Agent origin
    agent_id: str
    agent_role: str
    ai_decision_id: str | None = Field(
        default=None,
        description="Links to the AIDecision that produced this recommendation",
    )

    # Recommended action
    recommended_action: str = Field(description="Specific action recommended, e.g. 'initiate_promotion_workflow'")
    action_parameters: dict[str, Any] = Field(default_factory=dict)

    # Risk and approval
    risk_level: RiskLevel = Field(default=RiskLevel.LOW)
    requires_approval: bool = Field(default=False)
    confidence: float = Field(ge=0.0, le=1.0)
    priority: str = Field(default="NORMAL")

    # Supporting evidence
    evidence: list[str] = Field(default_factory=list)
    supporting_metrics: dict[str, Any] = Field(default_factory=dict)

    # Status tracking
    status: RecommendationStatus = Field(default=RecommendationStatus.PENDING)
    reviewer_id: str | None = Field(default=None)
    reviewer_decision_reason: str | None = Field(default=None)
    reviewed_at: datetime | None = Field(default=None)

    # Lifecycle
    expires_at: datetime | None = Field(default=None)
    correlation_id: str | None = Field(default=None)
    created_at: datetime = Field(default_factory=lambda: datetime.now(tz=UTC))
