"""enterprise_data_foundation

Revision ID: 996446598cc9
Revises: '017_executive_control_plane'
Create Date: 2026-09-02 13:05:13.018463
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '996446598cc9'
down_revision: Union[str, None] = '017_executive_control_plane'
branch_labels: Union[str, Sequence[str], None] = 'None'
depends_on: Union[str, Sequence[str], None] = 'None'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
