"""
HRMS Ports — Abstract Repository Interfaces for all 15 operational modules.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from collections.abc import Sequence
from datetime import date

from backend.hrms.domain.approvals import ApprovalRequest
from backend.hrms.domain.attendance import AttendanceRecord
from backend.hrms.domain.documents import EmployeeDocument
from backend.hrms.domain.employee import Employee
from backend.hrms.domain.learning import Course, CourseEnrollment
from backend.hrms.domain.leave import LeaveRequest
from backend.hrms.domain.organization import Department, Designation, Organization
from backend.hrms.domain.payroll import SalaryComponent
from backend.hrms.domain.performance import Goal, ReviewCycle
from backend.hrms.domain.policy import HRPolicy
from backend.hrms.domain.recruitment import Candidate, JobRequisition
from backend.hrms.domain.reports import HRReportDefinition, HRReportExecution
from backend.hrms.domain.role import Role
from backend.hrms.domain.skills import EmployeeSkill, Skill


class OrganizationRepository(ABC):
    @abstractmethod
    async def create(self, organization: Organization) -> Organization: ...
    @abstractmethod
    async def get_by_id(self, organization_id: str) -> Organization | None: ...
    @abstractmethod
    async def get_by_slug(self, slug: str) -> Organization | None: ...
    @abstractmethod
    async def update(self, organization: Organization) -> Organization: ...
    @abstractmethod
    async def list_all(self) -> Sequence[Organization]: ...


class DepartmentRepository(ABC):
    @abstractmethod
    async def create(self, department: Department) -> Department: ...
    @abstractmethod
    async def get_by_id(self, organization_id: str, department_id: str) -> Department | None: ...
    @abstractmethod
    async def get_by_code(self, organization_id: str, code: str) -> Department | None: ...
    @abstractmethod
    async def list_by_organization(self, organization_id: str) -> Sequence[Department]: ...
    @abstractmethod
    async def update(self, department: Department) -> Department: ...


class DesignationRepository(ABC):
    @abstractmethod
    async def create(self, designation: Designation) -> Designation: ...
    @abstractmethod
    async def get_by_id(self, organization_id: str, designation_id: str) -> Designation | None: ...
    @abstractmethod
    async def get_by_code(self, organization_id: str, code: str) -> Designation | None: ...
    @abstractmethod
    async def list_by_organization(self, organization_id: str) -> Sequence[Designation]: ...
    @abstractmethod
    async def update(self, designation: Designation) -> Designation: ...


class RoleRepository(ABC):
    @abstractmethod
    async def create(self, role: Role) -> Role: ...
    @abstractmethod
    async def get_by_id(self, organization_id: str, role_id: str) -> Role | None: ...
    @abstractmethod
    async def get_by_name(self, organization_id: str, name: str) -> Role | None: ...
    @abstractmethod
    async def list_by_organization(self, organization_id: str) -> Sequence[Role]: ...


class EmployeeRepository(ABC):
    @abstractmethod
    async def create(self, employee: Employee) -> Employee: ...
    @abstractmethod
    async def get_by_id(self, organization_id: str, employee_id: str) -> Employee | None: ...
    @abstractmethod
    async def get_by_code(self, organization_id: str, employee_code: str) -> Employee | None: ...
    @abstractmethod
    async def get_by_email(self, organization_id: str, email: str) -> Employee | None: ...
    @abstractmethod
    async def list_by_organization(
        self, organization_id: str, department_id: str | None = None, limit: int = 100, offset: int = 0
    ) -> Sequence[Employee]: ...
    @abstractmethod
    async def update(self, employee: Employee) -> Employee: ...


class SkillRepository(ABC):
    @abstractmethod
    async def create(self, skill: Skill) -> Skill: ...
    @abstractmethod
    async def get_by_id(self, organization_id: str, skill_id: str) -> Skill | None: ...
    @abstractmethod
    async def get_by_name(self, organization_id: str, name: str) -> Skill | None: ...
    @abstractmethod
    async def list_by_organization(self, organization_id: str) -> Sequence[Skill]: ...
    @abstractmethod
    async def update(self, skill: Skill) -> Skill: ...


class EmployeeSkillRepository(ABC):
    @abstractmethod
    async def create(self, employee_skill: EmployeeSkill) -> EmployeeSkill: ...
    @abstractmethod
    async def get_by_id(self, organization_id: str, employee_skill_id: str) -> EmployeeSkill | None: ...
    @abstractmethod
    async def get_by_employee_and_skill(self, organization_id: str, employee_id: str, skill_id: str) -> EmployeeSkill | None: ...
    @abstractmethod
    async def list_by_employee(self, organization_id: str, employee_id: str) -> Sequence[EmployeeSkill]: ...
    @abstractmethod
    async def update(self, employee_skill: EmployeeSkill) -> EmployeeSkill: ...


class EmployeeDocumentRepository(ABC):
    @abstractmethod
    async def create(self, document: EmployeeDocument) -> EmployeeDocument: ...
    @abstractmethod
    async def get_by_id(self, organization_id: str, document_id: str) -> EmployeeDocument | None: ...
    @abstractmethod
    async def list_by_employee(self, organization_id: str, employee_id: str) -> Sequence[EmployeeDocument]: ...
    @abstractmethod
    async def update(self, document: EmployeeDocument) -> EmployeeDocument: ...


class AttendanceRepository(ABC):
    @abstractmethod
    async def create_or_update(self, record: AttendanceRecord) -> AttendanceRecord: ...
    @abstractmethod
    async def get_by_employee_and_date(
        self, organization_id: str, employee_id: str, record_date: date
    ) -> AttendanceRecord | None: ...
    @abstractmethod
    async def list_by_employee(
        self, organization_id: str, employee_id: str, start_date: date, end_date: date
    ) -> Sequence[AttendanceRecord]: ...


class LeaveRepository(ABC):
    @abstractmethod
    async def create(self, request: LeaveRequest) -> LeaveRequest: ...
    @abstractmethod
    async def get_by_id(self, organization_id: str, leave_id: str) -> LeaveRequest | None: ...
    @abstractmethod
    async def list_by_employee(self, organization_id: str, employee_id: str) -> Sequence[LeaveRequest]: ...
    @abstractmethod
    async def update(self, request: LeaveRequest) -> LeaveRequest: ...


class PayrollRepository(ABC):
    @abstractmethod
    async def create_component(self, component: SalaryComponent) -> SalaryComponent: ...
    @abstractmethod
    async def list_components(self, organization_id: str) -> Sequence[SalaryComponent]: ...


class RecruitmentRepository(ABC):
    @abstractmethod
    async def create_requisition(self, req: JobRequisition) -> JobRequisition: ...
    @abstractmethod
    async def get_requisition(self, organization_id: str, requisition_id: str) -> JobRequisition | None: ...
    @abstractmethod
    async def list_requisitions(self, organization_id: str) -> Sequence[JobRequisition]: ...
    @abstractmethod
    async def create_candidate(self, candidate: Candidate) -> Candidate: ...
    @abstractmethod
    async def list_candidates(self, organization_id: str) -> Sequence[Candidate]: ...


class PerformanceRepository(ABC):
    @abstractmethod
    async def create_cycle(self, cycle: ReviewCycle) -> ReviewCycle: ...
    @abstractmethod
    async def list_cycles(self, organization_id: str) -> Sequence[ReviewCycle]: ...
    @abstractmethod
    async def create_goal(self, goal: Goal) -> Goal: ...
    @abstractmethod
    async def list_goals(self, organization_id: str, employee_id: str) -> Sequence[Goal]: ...


class LearningRepository(ABC):
    @abstractmethod
    async def create_course(self, course: Course) -> Course: ...
    @abstractmethod
    async def list_courses(self, organization_id: str) -> Sequence[Course]: ...
    @abstractmethod
    async def create_enrollment(self, enrollment: CourseEnrollment) -> CourseEnrollment: ...
    @abstractmethod
    async def list_enrollments(self, organization_id: str, employee_id: str) -> Sequence[CourseEnrollment]: ...


class PolicyRepository(ABC):
    @abstractmethod
    async def create_policy(self, policy: HRPolicy) -> HRPolicy: ...
    @abstractmethod
    async def get_policy(self, organization_id: str, policy_id: str) -> HRPolicy | None: ...
    @abstractmethod
    async def list_policies(self, organization_id: str) -> Sequence[HRPolicy]: ...


HRPolicyRepository = PolicyRepository


class ApprovalRepository(ABC):
    @abstractmethod
    async def create(self, request: ApprovalRequest) -> ApprovalRequest: ...
    @abstractmethod
    async def get_by_id(self, organization_id: str, approval_id: str) -> ApprovalRequest | None: ...
    @abstractmethod
    async def list_pending(self, organization_id: str) -> Sequence[ApprovalRequest]: ...
    @abstractmethod
    async def update(self, request: ApprovalRequest) -> ApprovalRequest: ...


class ReportRepository(ABC):
    @abstractmethod
    async def create_definition(self, definition: HRReportDefinition) -> HRReportDefinition: ...
    @abstractmethod
    async def list_definitions(self, organization_id: str) -> Sequence[HRReportDefinition]: ...
    @abstractmethod
    async def record_execution(self, execution: HRReportExecution) -> HRReportExecution: ...
