global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "hrms-backend"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["backend:8000"]
        labels:
          environment: "production"
          service: "hrms-api-gateway"

  - job_name: "hrms-redis"
    static_configs:
      - targets: ["redis:6379"]
        labels:
          service: "hrms-redis"

  - job_name: "hrms-postgres"
    static_configs:
      - targets: ["postgres:5432"]
        labels:
          service: "hrms-postgres"
